services:
  dockerlab.api:
    container_name: dockerlab.api
    build:
      context: ./DockerLab
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dockerlab.database
    ports:
      - "8080:8080"

  dockerlab.database:
    image: postgres:17.5-bullseye
    container_name: dockerlab.database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    name: dockerlab_db_data
